name: Build and Deploy

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Create .env
        run: |
          cat << EOF > apps/assassin/.env
          NEXT_PUBLIC_SUPABASE_URL=${{ secrets.SUPABASE_URL }}
          NEXT_PUBLIC_SUPABASE_ANON_KEY=${{ secrets.SUPABASE_ANON_KEY }}
          DATABASE_URL=${{ secrets.DATABASE_URL }}
          DIRECT_URL=${{ secrets.DIRECT_URL }}
          EOF

      - name: Generate Prisma Client
        run: pnpm assassin db:generate

      - name: Build
        run: pnpm assassin build

      - name: Package build artifacts
        run: |
          cd apps/assassin
          mkdir -p deploy

          cp -r .next/standalone/. deploy/

          mkdir -p deploy/apps/assassin/.next/static
          cp -r .next/static/. deploy/apps/assassin/.next/static/
          mkdir -p deploy/apps/assassin/public
          cp -r public/. deploy/apps/assassin/public/
          tar -czf ../../assassin.tar.gz -C deploy .

      - name: Upload bundle to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "assassin.tar.gz"
          target: "~"

      - name: Deploy & Run
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            rm -rf ~/SUNNYSIDE-CRUISE
            mkdir ~/SUNNYSIDE-CRUISE
            tar -xzf ~/assassin.tar.gz -C ~/SUNNYSIDE-CRUISE
            cd ~/SUNNYSIDE-CRUISE/apps/assassin
            pm2 describe assassin > /dev/null && pm2 restart assassin || pm2 start server.js --name assassin